---
name: Release the ansible collection
on:
  workflow_call:
    inputs:
      ah_publish:
        type: boolean
        default: true
      galaxy_publish:
        type: boolean
        default: true
    secrets:
      ah_token:
        required: true
      ansible_galaxy_api_key:
        required: true

jobs:
  release_ah:
    runs-on: ubuntu-latest
    environment: ah
    steps:
      - uses: actions/checkout@v3

      - name: "Build the collection"
        run: |
          ansible-galaxy collection build -v --force

      - name: "Publish collection on automation hub"
        if: ${{ github.event.inputs.ah_publish == 'true' }}
        run: |
          TARBALL=$(ls -1 ./*.tar.gz)
          cat << EOF > ansible.cfg
          [galaxy]
          server_list = rh_automation_hub
          [galaxy_server.rh_automation_hub]
          url=https://cloud.redhat.com/api/automation-hub/
          auth_url=https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
          token=${{ secrets.ah_token }}
          EOF
          ansible-galaxy collection publish "${TARBALL}"

      - name: "Publish the collection on galaxy"
        if: ${{ github.event.inputs.galaxy_publish == 'true' }}
        run: |
          TARBALL=$(ls -1 ./*.tar.gz)
          ansible-galaxy collection publish "${TARBALL}" --api-key "${{ secrets.ansible_galaxy_api_key }}"
